language: python

services:
  - docker

sudo: true

install:
  - docker build -t server-image .

script:
  - mkdir documentation && cd documentation
  - docker run -itd -v "$(pwd)":/web -p 8000:8000 --name sphinx-server server-image
  - docker ps | grep -q sphinx-server
  - docker exec -it sphinx-server sphinx-quickstart -q -p test -a tester -v 0.1
  - docker exec -it sphinx-server make html
  - curl -O http://localhost:8000/index.html
  - grep -q "Welcome to test’s documentation!" index.html
  - docker exec -it sphinx-server plantuml -version
